// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_selMpetCmuLuSoG6wqz4fEy0n_Ry1c',
    appId: '1:322977039798:web:66049de62ee18d95ed2d17',
    messagingSenderId: '322977039798',
    projectId: 'inventory-app-165a0',
    authDomain: 'inventory-app-165a0.firebaseapp.com',
    storageBucket: 'inventory-app-165a0.firebasestorage.app',
    measurementId: 'G-GM849VCRQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ZxDzslfKCv1HJlcwm2TC_2X3kL2ZGao',
    appId: '1:322977039798:android:1472ebeaa490c661ed2d17',
    messagingSenderId: '322977039798',
    projectId: 'inventory-app-165a0',
    storageBucket: 'inventory-app-165a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxUjeHu2Z00IuLgqdL8_GMg4MblFUCFc',
    appId: '1:322977039798:ios:a4077c2212994a31ed2d17',
    messagingSenderId: '322977039798',
    projectId: 'inventory-app-165a0',
    storageBucket: 'inventory-app-165a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxUjeHu2Z00IuLgqdL8_GMg4MblFUCFc',
    appId: '1:322977039798:ios:a4077c2212994a31ed2d17',
    messagingSenderId: '322977039798',
    projectId: 'inventory-app-165a0',
    storageBucket: 'inventory-app-165a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX_selMpetCmuLuSoG6wqz4fEy0n_Ry1c',
    appId: '1:322977039798:web:e03632839d76cb49ed2d17',
    messagingSenderId: '322977039798',
    projectId: 'inventory-app-165a0',
    authDomain: 'inventory-app-165a0.firebaseapp.com',
    storageBucket: 'inventory-app-165a0.firebasestorage.app',
    measurementId: 'G-5HE9YEJJZE',
  );

}